// Cart Related Events
export const ADD_TO_CART_EVENT = 'ADD_TO_CART_EVENT';
export const REMOVED_FROM_CART_EVENT = 'REMOVED_FROM_CART_EVENT';
export const DROPDOWN_TOGGLE_EVENT = 'DROPDOWN_TOGGLE_EVENT';
export const OVERLAY_CLICKED_EVENT = 'OVERLAY_CLICKED_EVENT';